name: ACDM
channels:
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=11.3.1
  - ffmpeg>=4.2.2
  - imageio>=2.9.0
  - ipython>=7.29.0
  - ipykernel>=6.4.2
  - matplotlib>=3.5.0
  - numpy>=1.22
  - pip
  - python>=3.0
  - pytorch::pytorch=1.11.*
  - pytorch::torchvision=0.12.0
  - scipy>=1.7.1
  - scikit-learn>=1.0
  - seaborn>=0.12
  - tensorboard>=2.6.0
  - tensorflow>=2.4.1
  - pip:
    - einops>=0.4.1
    - imageio-ffmpeg>=0.4.5
    - moviepy>=1.0
    # FNO dependecies that are not installed automatically by neuraloperator:
    - wandb
    - tensorly
    - tensorly-torch
    - torch-harmonics
    - neuraloperator
    - zarr